make_transform <- function(c_mat,
                           c_mat2, 
                           cmx_1,
                           cmx_2,
                           cmx_3,
                           cmx_4,
                           cmx_5,
                           cmx_6,
                           cmx_7,
                           cmx_8,
                           cmx_9,
                           adult_id, 
                           mu, 
                           school,
                           n_school_steps,
                           covid_step,
                           n_covid_steps,
                           n_age,
                           aging_vec,
                           ini,
                           pop,
                           scaling_fac,
                           vac_camp_cov,
                           vac_sche_cov) {
  
  function(theta) {

    theta_back<-c(
      beta_1 = theta[["beta_1"]]/scaling_fac[["beta_1"]],
      beta_2 = theta[["beta_2"]]/scaling_fac[["beta_2"]],
      beta_3 = theta[["beta_3"]]/scaling_fac[["beta_3"]],
      beta_4 = theta[["beta_4"]]/scaling_fac[["beta_4"]],
      maternalAB = theta[["maternalAB"]]/scaling_fac[["maternalAB"]],
      aduRR = theta[["aduRR"]]/scaling_fac[["aduRR"]],
      imm_yr = theta[["imm_yr"]]/scaling_fac[["imm_yr"]], 
      imm_fac = theta[["imm_fac"]]/scaling_fac[["imm_fac"]], 
      w1_1 = theta[["w1_1"]]/scaling_fac[["w1_1"]],
      repfac_0=theta[["repfac_0"]]/scaling_fac[["repfac_0"]],
      repfac_5=theta[["repfac_5"]]/scaling_fac[["repfac_5"]],
      repfac_15=theta[["repfac_15"]]/scaling_fac[["repfac_15"]],
      repfac_65p=theta[["repfac_65p"]]/scaling_fac[["repfac_65p"]],
      crossp_12=theta[["crossp_12"]]/scaling_fac[["crossp_12"]],
      crossp_21=theta[["crossp_21"]]/scaling_fac[["crossp_21"]],
      crossp_34=theta[["crossp_34"]]/scaling_fac[["crossp_34"]],
      crossp_43=theta[["crossp_43"]]/scaling_fac[["crossp_43"]]
    )
    
    
    c(list(
      pop  = pop,
      init  = ini,
      mu    = mu,
      m     = c_mat,
      m_holi= c_mat2,
      cmx_1=cmx_1,
      cmx_2=cmx_2,
      cmx_3=cmx_3,
      cmx_4=cmx_4,
      cmx_5=cmx_5,
      cmx_6=cmx_6,
      cmx_7=cmx_7,
      cmx_8=cmx_8,
      cmx_9=cmx_9,
      covid_step= as.double(covid_step),
      n_covid_steps= n_covid_steps,
      school_step= as.double(school),
      n_school_steps=n_school_steps,
      N_age = n_age,
      aging_vec = aging_vec,
      vac_camp_cov=vac_camp_cov,
      vac_sche_cov=vac_sche_cov),
      as.list(theta_back))
  }
}
